# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wobbly
description: >- # this means to ignore newlines until "baseurl:"
  Wobbly is a workplace organising platform, currently under development.
  We’re creating a space for energetic, powerful, and democratic unions to win struggles and grow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wobbly.app"
discord_link: https://discord.gg/KxC96yY
forum_link: https://discourse.wobbly.app/
wiki_link: https://wiki.wobbly.app/
github_link: https://github.com/Wobbly-App
donate_link: https://opencollective.com/wobbly

collections:
  - frontpage-sections

permalink: /:title:output_ext

defaults:
  - scope:
      path: "" # all files in the project
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
